### ISSUE TITLE
Support for EKS nodes resource

### ISSUE THREAD

**Issue by amukiza** [k1LoW/awspec#407]
#389 adding assertions for eks cluster nodes

AWS eks cluster does not have a way to retrieve and assert on the nodes (ec2 instances).  I am thinking we can find the ec2 instances (eks nodes) using either name tag and can therefore reuse a lot of the `Awspec::Type::Ec2`  functionality. 

**Example 1**

```
describe eks('my-eks') do 
  it { should be_running }
  ## Node assertions
  its(:nodes) { should belong_to_subnets(['my-subnet']) }
  its(:nodes) { should be_ready }
  its(:nodes) { should have_security_group('sg-abbu291') }
end
```

**Example 2**

```
describe eks_node('my-eks-node'), cluster: 'my-eks-cluster' do
  it { should be_ready }
  it { should have_security_group('sg-abbu291') }
  it { should belong_to_subnet(['my-subnet-0', 'my-subnet-1']) }
end
```

**Comment by k1LoW** [comment]
👀

**Comment by k1LoW** [comment]
@amukiza 

I like Example 2, if you can.  ( I can not find how to find nodes in [sdk doc](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EKS/Client.html#describe_cluster-instance_method))

Because
- The relationship between `eks` and `eks_node` is similar to the relationship between `ecs_cluster` and `ecs_container_instance`


[IMO] And, I like `eks_cluster` more than `eks`, because `eks_cluster` is a clearer name.

**Comment by amukiza** [comment]
@k1LoW  you are right. The relationship between an `eks_cluster` and its nodes is somewhat similar to `ecs_cluster` and `ecs_container_instance` only challenge is there is no equivalent of `describe_container_instances`. 

My thinking was that we could use a combination of `tags` and `security_groups`.  This won't be the accurate but it gives one a complete way of making assertions about both the cluster and the nodes. 

Alternatively, we could go for the option of using the `ec2` module 🤔and not add the `eks_cluster_node` type.

**Comment by jpratt3000-globality** [comment]
is this going in anytime soon? been 2 years

**Comment by glasswalk3r** [comment]
I would like to pick up this one... is anybody else working on it?

**Comment by glasswalk3r** [comment]
I did some digging and maybe we don't need to really on predefined labels because AWS already does that... well, at least for **managed node groups**.
There are actually [two types of EKS node groups](https://docs.aws.amazon.com/eks/latest/userguide/eks-compute.html) and looks like the API (at least based on it's description) works only for managed node groups. It would be required to test if really works like that but I really don't have any cluster running that to verify, so any help on that would be great.
So, for the managed node groups, we could [list them](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EKS/Client.html#list_nodegroups-instance_method) and [describe them](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EKS/Client.html#describe_nodegroup-instance_method) for whatever data we might need.
Finally, if the [result](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EKS/Types/DescribeNodegroupResponse.html#nodegroup-instance_method) of `describe_nodegroup` doesn't provide all the information required, than the logic described by @amukiza could be applied by using the provided [tags](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EKS/Types/Nodegroup.html#labels-instance_method) in the result.

**Comment by glasswalk3r** [comment]
Alright, I just created a [PR](https://github.com/k1LoW/awspec/pull/543) that implements those tests, but not exactly as suggested by @amukiza : we actually don't have `:nodes` implemented and I didn't see any need to do it in order to get those assertions.
Please also make sure to review the Markdown documentation explanation about `be_ready` limitations.

**Comment by glasswalk3r** [comment]
@k1LoW , since you merged my PR, I think this issue can be closed as well.

**Comment by k1LoW** [comment]
👍
